# Generated by Django 3.2.5 on 2021-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombres completos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Gestor de Recursos Humanos'), ('4', 'Analista de Gerencia'), ('5', 'Otro')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
